name = "test-01"

compatibility_date = "2023-11-15"
kv_namespaces = [{ binding = "KV", id = "999c4cf019a94b0eb439209c893a3356" }]

# the name what is it?
# tail_consumers = [{ service = "sentry-logger", environment = "production" }]

# [build]
# command = "pnpm build-ssr"
# watch_dir = "pages-gen"


[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "TEST"
database_id = "c0889c06-dc48-4322-aa87-71424c518696"
preview_database_id = "DB"                           # Required for Pages local development
